[phases.setup]
nixPkgs = ["ffmpeg", "curl"]

[phases.install]
cmds = [
  "npm install",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp",
  "chmod +x ./yt-dlp"
]

[start]
cmd = "node server.js"
